## 파일 입출력

In [1]:
import os
os.getcwd()

'C:\\Users\\Seon Jae Choi\\TIL\\mt28\\python\\ml'

In [2]:
import pandas as pd

sample_df = pd.DataFrame({"col1" : [1, 2], "col2" : [3,4]})
sample_df # 파일명 test.csv, index=False
csv_file_path = './output/test.csv'
sample_df.to_csv(csv_file_path, index=False, encoding='utf-8-sig')

## 파일 불러오기
- sample 폴더 안에 test.csv

In [3]:
df = pd.read_csv(filepath_or_buffer = csv_file_path)
df

col1  col2
0     1     3
1     2     4

In [4]:
df_boston = pd.read_csv(filepath_or_buffer = './data/boston.csv')
df_boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

## 열 및 행 선택
 - CRIM, ZN, INDUS 열을 선택함

In [5]:
cols = ['CRIM', 'ZN', 'INDUS'] # key error 발생 시 컬럼명을 잘못 기재
result = df_boston[cols]
result.head(1)

CRIM    ZN  INDUS
0  0.00632  18.0   2.31

## 행 추출의 기본원리는 조건문
 - ZN이 18.0에 해당하는 행만 추출

In [6]:
result = df_boston[df_boston['ZN'] == 18.0]
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  target  
0  396.9   4.98    24.0

In [7]:
result = df_boston[df_boston['AGE'] >= 50].reset_index(drop = True)
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
4    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
354  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
355  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
356  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
357  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
358  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  396.90   5.33    36.2  
4       18.7  394.12   5.21    28.7  
..       ...     ...    ...     ...  
354     21.0  391.99   9.67    22.4  
355     21.0  396.90   9.08    20.6  
356     21.0  396.90   5.64    23.9  
357     21.0  393.45   6.48    22.0  
358     21.0  396.90   7.88    11.9  

[359 rows x 14 columns]

 - INDUS가 5.0 이상이면서, B가 394 이상인 데이터 추출

In [8]:
# and = df_boston[(조건식1) & (조건식2)] // or = df_boston[(조건식1) | (조건식2)]
result = df_boston[(df_boston['INDUS'] >= 5.0) & (df_boston['B'] >= 394)].reset_index(drop = True)
result.head(1)

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0  0.02731  0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0     17.8   

       B  LSTAT  target  
0  396.9   9.14    21.6

## iloc와 loc 문법

In [9]:
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [10]:
# %%timeit
# iloc 활용해서 추출
df1 = df_boston.iloc[0:3, 0:3]
df1

CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07
2  0.02729   0.0   7.07

In [11]:
# %%timeit
# loc 활용해서 추출
df2 = df_boston.loc[0:2, :'INDUS']
df2

CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07
2  0.02729   0.0   7.07

In [12]:
result = df_boston.loc[(df_boston['INDUS'] >= 5.0) & (df_boston['B'] >= 394) # 행
                       , ['CRIM', 'ZN', 'INDUS']].reset_index(drop=True)     # 열
result.head()

CRIM    ZN  INDUS
0  0.02731   0.0   7.07
1  0.08829  12.5   7.87
2  0.14455  12.5   7.87
3  0.11747  12.5   7.87
4  0.62976   0.0   8.14

In [13]:
result = df_boston.loc[(df_boston['INDUS'] >= 5.0) & (df_boston['B'] >= 394)
                       , df_boston.columns[0:3]].reset_index(drop=True)
result.head()

CRIM    ZN  INDUS
0  0.02731   0.0   7.07
1  0.08829  12.5   7.87
2  0.14455  12.5   7.87
3  0.11747  12.5   7.87
4  0.62976   0.0   8.14

## 결측치 다루기

In [14]:
import pandas as pd
import numpy as np

np.random.seed(0) # 초전도체 현상, 실험조건을 동일하게 맞추기 위해
data = np.random.randint(0, 10, size = (10, 3)).astype(float)
print(data)

[[5. 0. 3.]
 [3. 7. 9.]
 [3. 5. 2.]
 [4. 7. 6.]
 [8. 8. 1.]
 [6. 7. 7.]
 [8. 1. 5.]
 [9. 8. 9.]
 [4. 3. 0.]
 [3. 5. 0.]]


In [15]:
data[data < 3] = np.nan
print(data)

[[ 5. nan  3.]
 [ 3.  7.  9.]
 [ 3.  5. nan]
 [ 4.  7.  6.]
 [ 8.  8. nan]
 [ 6.  7.  7.]
 [ 8. nan  5.]
 [ 9.  8.  9.]
 [ 4.  3. nan]
 [ 3.  5. nan]]


In [16]:
df = pd.DataFrame(data, columns = ["col1", "col2", "col3"]) # 외부에서 새로운 데이터 가져옴
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     float64
 1   col2    8 non-null      float64
 2   col3    6 non-null      float64
dtypes: float64(3)
memory usage: 368.0 bytes


In [17]:
df.isna().sum()

col1    0
col2    2
col3    4
dtype: int64

In [18]:
# 결측치 평균으로 대치 해보기
mean_values = df.mean()  # 각 열의 평균 계산
print(mean_values, end='\n\n') # , end='\n\n' 한칸 띄우기
# print()

df_filled = df.fillna(mean_values)  # 결측치를 각 열의 평균으로 대체
print(df_filled)

col1    5.30
col2    6.25
col3    6.50
dtype: float64

   col1  col2  col3
0   5.0  6.25   3.0
1   3.0  7.00   9.0
2   3.0  5.00   6.5
3   4.0  7.00   6.0
4   8.0  8.00   6.5
5   6.0  7.00   7.0
6   8.0  6.25   5.0
7   9.0  8.00   9.0
8   4.0  3.00   6.5
9   3.0  5.00   6.5


In [19]:
# 결측치 평균으로 대치 해보기 step 02
col3_mean = df['col3'].mean()
col3_mean
df['col3'] = df['col3'].fillna(col3_mean)
df['col2'] = df['col2'].fillna(df['col2'].mean())
df

col1  col2  col3
0   5.0  6.25   3.0
1   3.0  7.00   9.0
2   3.0  5.00   6.5
3   4.0  7.00   6.0
4   8.0  8.00   6.5
5   6.0  7.00   7.0
6   8.0  6.25   5.0
7   9.0  8.00   9.0
8   4.0  3.00   6.5
9   3.0  5.00   6.5

## 행 추가

In [20]:
df = pd.DataFrame({
    "이름": ["Evan", "Sara", "Chris", "Messi", "Woods", "Jordan"], 
    "국어": [70, 90, None, None, 100, 85], 
    "영어": [65, 100, None, 90, 70, 80]
})

df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0

In [21]:
# 행 추가
df.loc[6, "이름":"영어"] = ["kim", 50, 60]
df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0
6     kim   50.0   60.0

In [22]:
%%timeit
# 국어 점수가 90점 이상이면 "A"
# 국어 점수가 80점 ~ 89점 "B"
# 국어 점수가 70점 ~ 79점 "C"
# 나머지는 F

# 성적기반 등급분류 함수
def get_grade(score):
    if score >= 90:
        return 'A'
    elif 80 <= score < 90: 
        return 'B'
    elif 70 <= score < 80: 
        return 'C'
    else:
        return 'F'
        
# 국어 점수기반으로 함수를 사용해 국어점수 등급분류
df['등급'] = df['국어'].apply(get_grade)
df

143 µs ± 1.93 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


 - numpy.where, 조건식 한번만 적용
 if 조건식, 참일 때, 거짓일 때

In [23]:
# np.where(조건식, 참, np.where(조건식, 참, np.where(조건식, 참)))
# np.select(다중조건식, 다중결괏값, default = else 조건)

In [24]:
%%timeit
condition_list = [(df["국어"] >= 90), (df['국어'] >= 80) & (df['국어'] < 90), (df['국어'] >= 70) & (df['국어'] < 80)]
choice_list = ["A", "B", "C"]
df['점수'] = np.select(condition_list, choice_list, default = "F")
df

427 µs ± 7.25 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## 날짜 데이터 핸들링

In [25]:
date_string = "2023-03-02"
# type(date_string) = str

datetime_obj = pd.to_datetime(date_string)
# print(datetime_obj) = 2023-03-02 00:00:00
# print(type(datetime_obj)) = <class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [26]:
date_list = ["2023-03-02"]
print(type(date_list))

datetime_obj = pd.to_datetime(date_list)
print(datetime_obj)
print(type(datetime_obj))

<class 'list'>
DatetimeIndex(['2023-03-02'], dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


## 데이터 가져오기
 - raw_sale.csv 파일 가져오기

In [27]:
sales = pd.read_csv('data/raw_sales.csv')
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   datesold      29580 non-null  object
 1   postcode      29580 non-null  int64 
 2   price         29580 non-null  int64 
 3   propertyType  29580 non-null  object
 4   bedrooms      29580 non-null  int64 
dtypes: int64(3), object(2)
memory usage: 1.1+ MB


In [28]:
# 날짜 데이터 변환
sales.head(1)

datesold  postcode   price propertyType  bedrooms
0  2007-02-07 00:00:00      2607  525000        house         4

In [29]:
# 연도, 월, 일
sales['year'] = sales['datesold'].dt.year
sales['month'] = sales['datesold'].dt.month
sales['day'] = sales['datesold'].dt.day
sales.info()

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
sales['datesold'] = pd.to_datetime(sales['datesold'])
sales.info()

In [ ]:
# 연도, 월, 일
sales['year'] = sales['datesold'].dt.year
sales['month'] = sales['datesold'].dt.month
sales['day'] = sales['datesold'].dt.day
sales

## shift 기능

In [ ]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df.head(3)

In [ ]:
temp_df['shifted_v1'] = temp_df['price'].shift(1, fill_value=0).astype(int)
temp_df['diff'] = temp_df['price'] - temp_df['shifted_v1']
temp_df.head(5)

In [ ]:
temp_df['shifted_v2'] = temp_df['price'].shift(2, fill_value=0).astype(int)
temp_df['diff2'] = temp_df['price'] - temp_df['shifted_v2']
temp_df.head(5)

In [ ]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df['shifted_v3'] = temp_df['price'].shift(-1, fill_value=0).astype(int)
temp_df['shifted_v4'] = temp_df['price'].shift(-2, fill_value=0).astype(int)
temp_df.tail(5)

In [ ]:
sales.info()

In [ ]:
sales['한글날짜'] = sales['datesold'].dt.strftime('%Y년 %m월 %d일')
sales.head(3)

## 결측치 이상치 데이터 핸들링

In [30]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import statsmodels
import scipy
import seaborn as sns

print(pd.__version__)
print(np.__version__)
print(matplotlib.__version__)
print(statsmodels.__version__)
print(scipy.__version__)
print(sns.__version__)

2.0.3
1.25.2
3.7.2
0.14.0
1.11.1
0.12.2


In [31]:
DATA_PATH = './'
covidtotals = pd.read_csv(DATA_PATH + "data/covidtotalswithmissings.csv")
covidtotals.head(5)

iso_code    lastdate     location  total_cases  total_deaths  \
0      AFG  2020-06-01  Afghanistan        15205           257   
1      ALB  2020-06-01      Albania         1137            33   
2      DZA  2020-06-01      Algeria         9394           653   
3      AND  2020-06-01      Andorra          764            51   
4      AGO  2020-06-01       Angola           86             4   

   total_cases_pm  total_deaths_pm  population  pop_density  median_age  \
0         390.589            6.602  38928341.0       54.422        18.6   
1         395.093           11.467   2877800.0      104.871        38.0   
2         214.225           14.891  43851043.0       17.348        29.1   
3        9888.048          660.066     77265.0      163.755         NaN   
4           2.617            0.122  32866268.0       23.890        16.8   

   gdp_per_capita  hosp_beds  
0        1803.987       0.50  
1       11803.431       2.89  
2       13913.839       1.90  
3             NaN        NaN  
4        5819.495        NaN

In [32]:
covidtotals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   iso_code         210 non-null    object 
 1   lastdate         210 non-null    object 
 2   location         210 non-null    object 
 3   total_cases      210 non-null    int64  
 4   total_deaths     210 non-null    int64  
 5   total_cases_pm   209 non-null    float64
 6   total_deaths_pm  209 non-null    float64
 7   population       210 non-null    float64
 8   pop_density      198 non-null    float64
 9   median_age       186 non-null    float64
 10  gdp_per_capita   182 non-null    float64
 11  hosp_beds        164 non-null    float64
dtypes: float64(7), int64(2), object(3)
memory usage: 19.8+ KB


In [33]:
pd.set_option('display.width', 80)
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 20)
pd.options.display.float_format = '{:,.2f}'.format

In [34]:
covidtotals = covidtotals.set_index('iso_code')
covidtotals.head()

lastdate     location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                       
AFG       2020-06-01  Afghanistan        15205           257          390.59   
ALB       2020-06-01      Albania         1137            33          395.09   
DZA       2020-06-01      Algeria         9394           653          214.22   
AND       2020-06-01      Andorra          764            51        9,888.05   
AGO       2020-06-01       Angola           86             4            2.62   

          total_deaths_pm    population  pop_density  median_age  \
iso_code                                                           
AFG                  6.60 38,928,341.00        54.42       18.60   
ALB                 11.47  2,877,800.00       104.87       38.00   
DZA                 14.89 43,851,043.00        17.35       29.10   
AND                660.07     77,265.00       163.75         NaN   
AGO                  0.12 32,866,268.00        23.89       16.80   

          gdp_per_capita  hosp_beds  
iso_code                             
AFG             1,803.99       0.50  
ALB            11,803.43       2.89  
DZA            13,913.84       1.90  
AND                  NaN        NaN  
AGO             5,819.49        NaN

### 결측치 처리
 - 인구통계 컬럼에서 결측치 데이터 확인
 - 컬럼 방향으로 결측치의 갯수를 파악함
 - 5가지 인구 통계 변수 중에서 3개가 누락된 곳, 4개가 누락된 곳 확인

In [36]:
# totvars = 코비드 바이러스 확진자 관련 변수
totvars = ['location','total_cases','total_deaths','total_cases_pm','total_deaths_pm']
# demovars = 인구수 관련 변수
demovars = ['population','pop_density','median_age','gdp_per_capita', 'hosp_beds']

In [38]:
covidtotals[demovars].isnull().sum(axis=0)

population         0
pop_density       12
median_age        24
gdp_per_capita    28
hosp_beds         46
dtype: int64

In [40]:
covidtotals.iloc[2:4, :]

lastdate location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                   
DZA       2020-06-01  Algeria         9394           653          214.22   
AND       2020-06-01  Andorra          764            51        9,888.05   

          total_deaths_pm    population  pop_density  median_age  \
iso_code                                                           
DZA                 14.89 43,851,043.00        17.35       29.10   
AND                660.07     77,265.00       163.75         NaN   

          gdp_per_capita  hosp_beds  
iso_code                             
DZA            13,913.84       1.90  
AND                  NaN        NaN

In [48]:
demovars_misscnt = covidtotals[demovars].isnull().sum(axis=1)
demovars_misscnt.value_counts()

0    156
1     24
2     12
3     10
4      8
Name: count, dtype: int64

### 미션1.
 - 결측치가 3개 이상인 데이터를 추출하세요!
 - 추출해야할 컬럼은 ['location'] + demovars

In [54]:
covidtotals.loc[demovars_misscnt >= 3, ['location'] + demovars].T

iso_code             AND       AIA                              BES  \
location         Andorra  Anguilla  Bonaire Sint Eustatius and Saba   
population     77,265.00 15,002.00                        26,221.00   
pop_density       163.75       NaN                              NaN   
median_age           NaN       NaN                              NaN   
gdp_per_capita       NaN       NaN                              NaN   
hosp_beds            NaN       NaN                              NaN   

iso_code                           VGB             FRO               FLK  \
location        British Virgin Islands  Faeroe Islands  Falkland Islands   
population                   30,237.00       48,865.00          3,483.00   
pop_density                     207.97           35.31               NaN   
median_age                         NaN             NaN               NaN   
gdp_per_capita                     NaN             NaN               NaN   
hosp_beds                          NaN             NaN               NaN   

iso_code              GIB        GRL       GGY          IMN        JEY  \
location        Gibraltar  Greenland  Guernsey  Isle of Man     Jersey   
population      33,691.00  56,772.00 67,052.00    85,032.00 101,073.00   
pop_density      3,457.10       0.14       NaN       147.87        NaN   
median_age            NaN        NaN       NaN          NaN        NaN   
gdp_per_capita        NaN        NaN       NaN          NaN        NaN   
hosp_beds             NaN        NaN       NaN          NaN        NaN   

iso_code                XKX         MSR                       MNP  \
location             Kosovo  Montserrat  Northern Mariana Islands   
population     1,932,774.00    4,999.00                 57,557.00   
pop_density             NaN         NaN                    119.88   
median_age              NaN         NaN                       NaN   
gdp_per_capita          NaN         NaN                       NaN   
hosp_beds               NaN         NaN                       NaN   

iso_code                 TWN                       TCA      VAT  \
location              Taiwan  Turks and Caicos Islands  Vatican   
population     23,816,775.00                 38,718.00   809.00   
pop_density              NaN                     37.31      NaN   
median_age             42.20                       NaN      NaN   
gdp_per_capita           NaN                       NaN      NaN   
hosp_beds                NaN                       NaN      NaN   

iso_code                   ESH  
location        Western Sahara  
population          597,330.00  
pop_density                NaN  
median_age               28.40  
gdp_per_capita             NaN  
hosp_beds                  NaN

## Index Alignment
 - 인덱스의 값끼리 연산이 이뤄지는 것을 말함. Pandas에서 제공함

In [60]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])

print(s1, "\n", s2)
print(s1 + s2)

a    1
b    2
c    3
d    4
dtype: int64 
 d    4
c    3
b    2
a    1
dtype: int64
a    2
b    4
c    6
d    8
dtype: int64


## 코로나 관련 변수만 추출
 - 결측치가 있는지 확인
 - 결측치가 존재하는 국가 하나 존재
 - totvars 사용

In [84]:
totvars_misscnt = covidtotals[totvars].isnull().sum(axis=1)
totvars_misscnt.value_counts()
ms_country = covidtotals.loc[totvars_misscnt > 1, ['location'] + totvars]
ms_country.T

iso_code               HKG
location         Hong Kong
location         Hong Kong
total_cases              0
total_deaths             0
total_cases_pm         NaN
total_deaths_pm        NaN

In [87]:
covidtotalsonly = covidtotals.loc[:, totvars]
covidtotalsonly['total_cases_q'] = pd.qcut(covidtotalsonly['total_cases'],
                                          labels = ['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                          q = 5, precision=0)

covidtotalsonly['total_deaths_q'] = pd.qcut(covidtotalsonly['total_deaths'],
                                          labels = ['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                          q = 5, precision=0)
covidtotalsonly

location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                              
AFG          Afghanistan        15205           257          390.59   
ALB              Albania         1137            33          395.09   
DZA              Algeria         9394           653          214.22   
AND              Andorra          764            51        9,888.05   
AGO               Angola           86             4            2.62   
...                  ...          ...           ...             ...   
VNM              Vietnam          328             0            3.37   
ESH       Western Sahara           23             1           38.51   
YEM                Yemen          323            80           10.83   
ZMB               Zambia         1057             7           57.50   
ZWE             Zimbabwe          178             4           11.98   

          total_deaths_pm total_cases_q total_deaths_q  
iso_code                                                
AFG                  6.60            높음             높음  
ALB                 11.47            중간             중간  
DZA                 14.89            높음           매우높음  
AND                660.07            중간             중간  
AGO                  0.12          매우낮음             낮음  
...                   ...           ...            ...  
VNM                  0.00            낮음           매우낮음  
ESH                  1.67          매우낮음           매우낮음  
YEM                  2.68            낮음             높음  
ZMB                  0.38            중간             낮음  
ZWE                  0.27            낮음             낮음  

[210 rows x 7 columns]

In [88]:
pd.crosstab(covidtotalsonly['total_cases_q'], covidtotalsonly['total_deaths_q'])

total_deaths_q  매우낮음  낮음  중간  높음  매우높음
total_cases_q                         
매우낮음              34   7   1   0     0
낮음                12  19  10   1     0
중간                 1  13  15  13     0
높음                 0   0  12  24     6
매우높음               0   0   2   4    36

In [95]:
covidtotals.loc[(covidtotalsonly.total_cases_q=="매우높음") & (covidtotalsonly.total_deaths_q=="중간")].T

iso_code                 QAT          SGP
lastdate          2020-06-01   2020-06-01
location               Qatar    Singapore
total_cases            56910        34884
total_deaths              38           23
total_cases_pm     19,753.15     5,962.73
total_deaths_pm        13.19         3.93
population      2,881,060.00 5,850,343.00
pop_density           227.32     7,915.73
median_age             31.90        42.40
gdp_per_capita    116,935.60    85,535.38
hosp_beds               1.20         2.40

In [96]:
covidtotals.loc[(covidtotalsonly.total_cases_q=="매우낮음") & (covidtotalsonly.total_deaths_q=="중간")].T

iso_code                               SXM
lastdate                        2020-06-01
location         Sint Maarten (Dutch part)
total_cases                             77
total_deaths                            15
total_cases_pm                    1,795.62
total_deaths_pm                     349.80
population                       42,882.00
pop_density                       1,209.09
median_age                             NaN
gdp_per_capita                   36,327.23
hosp_beds                              NaN

In [97]:
covidtotals.loc[(covidtotalsonly.total_cases_q=="낮음") & (covidtotalsonly.total_deaths_q=="높음")].T

iso_code                  YEM
lastdate           2020-06-01
location                Yemen
total_cases               323
total_deaths               80
total_cases_pm          10.83
total_deaths_pm          2.68
population      29,825,968.00
pop_density             53.51
median_age              20.30
gdp_per_capita       1,479.15
hosp_beds                0.70